name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at 3:00 AM
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&border_radius=0
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=donut&theme=tokyonight&border_radius=0
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Assets Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git checkout --orphan cardUpdates
          git rm -rf . --quiet
          
          git add profile/*.svg
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "docs: update profile stats [skip ci]"
            git push origin assets --force
          else
            echo "No changes detected, skipping push."
          fi
